# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    twig:
        mode: lazy

    driver: "gd"
    resolvers:
        default:
            web_path:
                web_root: "%kernel.project_dir%/public"

    default_filter_set_settings:
        format: webp

    webp:
        generate: true

    filter_sets:
        cache: ~

        admin_product_thumb_jpeg:
            format: jpeg
            quality: 75
            filters:
                thumbnail: { size: [48, 48], mode: inset }
        admin_product_thumb_webp:
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [48, 48], mode: inset }
        product_thumb_jpeg:
            format: jpeg
            quality: 75
            filters:
                thumbnail: { size: [400, 400], mode: inset }
        product_thumb_webp:
            format: webp
            quality: 100
            filters:
                thumbnail: { size: [400, 400], mode: inset }
