vich_uploader:
    db_driver: orm

    mappings:
        avatars:
            uri_prefix: /uploads/avatars
            upload_destination: '%kernel.project_dir%/public/uploads/avatars'
            namer:
                service: Vich\UploaderBundle\Naming\PropertyNamer
                options:
                    property: id
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
        products:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
