# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    admin_prefix: '%env(resolve:ADMIN_PREFIX)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        bind:
            $adminPrefix: '%admin_prefix%'
            $appEnv: '%kernel.environment%'
    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Admin\Controller\:
        resource: '../src/Admin/Controller'
        tags: ['controller.service_arguments']

#    App\Api\Controller\:
#        resource: '../src/Api/Controller'
#        tags: ['controller.service_arguments']

    App\Client\Controller\:
        resource: '../src/Client/Controller'
        tags: ['controller.service_arguments']

    Knp\Bundle\PaginatorBundle\Helper\Processor:
        tags: ['knp_paginator.helper.processor']

#    App\Infrastructure\Controller\:
#        resource: '../src/Infrastructure/Controller'
#        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    Bezhanov\Faker\Provider\Commerce: ~
